from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from typing import List
from core.schemas.venta_schema import PedidoCreate, PedidoResponse
from infra.db.database import get_db
from core.services.pedido_service import PedidoService

router = APIRouter(prefix="/api/pedidos", tags=["Gestión de Pedidos"])

@router.post("/")
def registrar_pedido_ia(data: PedidoCreate, db: Session = Depends(get_db)):
    """Receives order drafts generated by the NLP chatbot and stores them."""
    servicio = PedidoService(db)
    try:
        return servicio.registrar_nuevo_pedido(data)
    except ValueError as e:
        raise HTTPException(status_code=409, detail=str(e))

@router.get("/mesa/{nro_mesa}")
def ver_pedidos_mesa(nro_mesa: int, db: Session = Depends(get_db)):
    """Retrieves all order details associated with a specific table."""
    servicio = PedidoService(db)
    return servicio.listar_pedidos_mesa(nro_mesa)

@router.get("/", response_model=List[PedidoResponse])
def listar_todos_pedidos(db: Session = Depends(get_db)):
    """Lists all registered orders."""
    servicio = PedidoService(db)
    return servicio.listar_todos_pedidos()

@router.put("/{id_pedido}/confirmar")
def confirmar_pedido_cocina(id_pedido: int, db: Session = Depends(get_db)):
    """Confirms a pending order draft and queues it for kitchen preparation."""
    servicio = PedidoService(db)
    return servicio.confirmar_pedido_ia(id_pedido)

@router.put("/{id_pedido}/pagar")
def pagar_pedido(id_pedido: int, metodo_pago: str = "EFECTIVO", 
                 monto_efectivo: float = 0.0, monto_yape: float = 0.0, monto_tarjeta: float = 0.0,
                 db: Session = Depends(get_db)):
    """Registers payment transaction details for a specific order."""
    servicio = PedidoService(db)
    try:
        return servicio.pagar_pedido(
            id_pedido, 
            metodo_pago=metodo_pago,
            monto_efectivo=monto_efectivo,
            monto_yape=monto_yape,
            monto_tarjeta=monto_tarjeta
        )
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))

@router.put("/{id_pedido}/anular")
def anular_pedido(id_pedido: int, db: Session = Depends(get_db)):
    """Annullas/cancels a specific active order."""
    servicio = PedidoService(db)
    return servicio.cancelar_o_anular_pedido(id_pedido)

@router.put("/{id_pedido}/preparar")
def preparar_pedido_cocina(id_pedido: int, db: Session = Depends(get_db)):
    """Cambia el estado del pedido en cocina a PREPARANDO."""
    servicio = PedidoService(db)
    return servicio.pedido_repo.actualizar_estado(id_pedido, "PREPARANDO", "PENDIENTE")

@router.put("/{id_pedido}/listo")
def completar_pedido_cocina(id_pedido: int, db: Session = Depends(get_db)):
    """Cambia el estado del pedido en cocina a LISTO."""
    servicio = PedidoService(db)
    return servicio.pedido_repo.actualizar_estado(id_pedido, "LISTO", "PENDIENTE")